/**
 * @file src/data.ts
 * Static data tables for the bnl extension: keywords, phonetic aliases,
 * globals, module members, intrinsics, and import-name canonicalization.
 */

// keyword groups (English ↔ Bangla)
export const KEYWORD_GROUPS: Record<string, string[]> = {
    if:       ["if",        "যদি"],
    else:     ["else",      "নাহলে"],
    while:    ["while",     "যতক্ষণ"],
    for:      ["for",       "প্রতি"],
    of:       ["of",        "এর"],
    function: ["function",  "ফাংশন"],
    return:   ["return",    "ফেরত"],
    var:      ["var",       "চলক",       "ধরি"],
    class:    ["class",     "শ্রেণী"],
    extends:  ["extends",   "প্রসারিত"],
    super:    ["super",     "উপরের"],
    import:   ["import",    "আমদানি"],
    as:       ["as",        "যেমন"],
    and:      ["and",       "এবং"],
    or:       ["or",        "অথবা"],
    not:      ["not",       "না"],
    true:     ["true",      "সত্য"],
    false:    ["false",     "মিথ্যা"],
    null:     ["null",      "নাই",       "নাল"],
    try:      ["try",       "চেষ্টা"],
    catch:    ["catch",     "ধরুন"],
    throw:    ["throw",     "নিক্ষেপ"],
    finally:  ["finally",   "অবশেষে"],
    switch:   ["switch",    "বিকল্প"],
    case:     ["case",      "অবস্থা"],
    default:  ["default",   "অন্যথায়"],
    break:    ["break",     "থামুন"],
    continue: ["continue",  "চলুন"],
};

export const ALL_KEYWORDS = [...new Set(Object.values(KEYWORD_GROUPS).flat())];

// phonetic (roman → bangla)
export const PHONETIC_ALIASES: Record<string, string[]> = {
    // keywords
    "যদি":      ["jodi"],
    "নাহলে":    ["nahole", "naholay"],
    "যতক্ষণ":   ["jotokkhon", "jotoxon"],
    "প্রতি":    ["proti"],
    "এর":       ["er"],
    "ফাংশন":    ["fangshon", "fangson", "funcSon"],
    "ফেরত":     ["ferot"],
    "চলক":      ["cholok"],
    "ধরি":      ["dhori"],
    "শ্রেণী":   ["sreni", "shreni"],
    "প্রসারিত": ["prosarito"],
    "উপরের":    ["uporer"],
    "আমদানি":   ["amdani"],
    "যেমন":     ["jemon"],
    "এবং":      ["ebong"],
    "অথবা":     ["othoba"],
    "না":       ["na"],
    "সত্য":     ["sotto", "sotyo"],
    "মিথ্যা":   ["mittha", "mithya"],
    "নাই":      ["nai"],
    "নাল":      ["nal"],
    "চেষ্টা":   ["chesta", "cheshta"],
    "ধরুন":     ["dhorun"],
    "নিক্ষেপ":  ["nikkhep"],
    "অবশেষে":   ["oboseshe", "obosheshe"],
    "বিকল্প":   ["bikolpo"],
    "অবস্থা":   ["obostha"],
    "অন্যথায়": ["onnothay", "onyothay"],
    "থামুন":    ["thamun"],
    "চলুন":     ["cholun"],
    // Bangla globals
    "লিখুন":    ["likhun"],
    "ধরণ":      ["dhoron"],
    // built-in module aliases
    "ফাইল":         ["fail", "file"],
    "সিস্টেম":      ["sistem", "system"],
    "টাইমার":       ["taimar", "timer"],
    "নেট":          ["net"],
    "জেসন":         ["jeson", "json"],
    "সময়":          ["somoy", "somay"],
    "পথ":           ["poth", "path"],
    "গণিত":         ["gonit", "math"],
    "এলোমেলো":     ["elomelo", "random"],
    "ক্রিপ্টো":     ["kripto", "crypto"],
    "প্যাটার্ন":     ["pattern", "patern"],
    "এইচটিটিপি":    ["http"],
    "টিএলএস":       ["tls"],
    "অনুরোধ":       ["onurodh", "request"],
    "ওয়েব":        ["web", "oyeb"],
    "ইউআরএল":       ["url"],
    "লগ":           ["log"],
    "টেস্ট":        ["test", "tesht"],
    "সংকোচন":      ["shongkochon", "zlib"],
    "এসকিউলাইট":    ["sqlite"],
    "পোস্টগ্রেস":    ["pg", "postgres"],
    "মাইএসকিউএল":   ["mysql"],
    "মঙ্গো":        ["mongo"],
    "চালান":        ["chalan", "exec"],
    "ডিএনএস":       ["dns"],
    "টেমপ্লেট":     ["template", "templet"],
    "ওয়েবসকেট":   ["ws", "websocket"],
    "কুকি":          ["kuki", "cookie"],
    "অধিবেশন":     ["odhibeshon", "session"],
    "মাল্টিপার্ট":   ["multipart"],
    "ডটএনভ":        ["dotenv"],
    "কমান্ড":       ["command", "kommand", "cli"],
    "ইউইউআইডি":     ["uuid"],
    "সিএসভি":       ["csv"],
};

// global builtins

export type Global = { name: string; detail: string; doc: string; snippet?: string };

export const GLOBALS: Global[] = [
    { name: "print",     detail: "print(...args) -> null",         doc: "Print values space-separated, then a newline.", snippet: "print(${0})" },
    { name: "লিখুন",     detail: "লিখুন(...) -> null",              doc: "Bangla alias of `print`.",                       snippet: "লিখুন(${0})" },
    { name: "str",       detail: "str(value) -> string",           doc: "Convert any value to its display string.",        snippet: "str(${1:value})" },
    { name: "type",      detail: "type(value) -> string",          doc: "Returns one of: null, bool, number, string, function, class, instance, module, list, map.", snippet: "type(${1:value})" },
    { name: "ধরণ",       detail: "ধরণ(value) -> string",            doc: "Bangla alias of `type`.",                         snippet: "ধরণ(${1:value})" },
    { name: "to_number", detail: "to_number(s) -> number | null",  doc: "Parse a string to a number; returns null on failure.", snippet: "to_number(${1:s})" },
    { name: "chr",       detail: "chr(n) -> string",               doc: "Single-byte string from a byte value (0..255).",  snippet: "chr(${1:n})" },
    { name: "try_call",  detail: "try_call(thunk, on_err) -> any", doc: "Call thunk(); on RuntimeError or throw, call on_err(message_or_value) instead.", snippet: "try_call(\n    function () { return ${1:expr}; },\n    function (${2:err}) { return ${0:fallback}; }\n)" },
];

// module member tables (sys / io / timers)

export type Member = { name: string; detail: string; doc?: string; snippet?: string };
const fn = (name: string, detail: string, doc?: string, snippet?: string): Member => ({ name, detail, doc, snippet });

export const MODULES: Record<string, Member[]> = {
    sys: [
        fn("platform", "sys.platform: string", "OS identifier: 'windows' | 'linux' | 'darwin' | ..."),
        fn("argc",     "sys.argc() -> number",       "Number of script args."),
        fn("arg",      "sys.arg(i) -> string|null",  "i-th script arg, or null if out of range.", "arg(${1:i})"),
        fn("env",      "sys.env(name) -> string|null", "Env var, or null if unset.",              "env(${1:\"NAME\"})"),
        fn("exit",     "sys.exit(code) -> never",    "Terminate with the given exit code.",      "exit(${1:0})"),
    ],

    io: [
        // sync
        fn("read_file",   "io.read_file(path) -> string",          "Read entire file contents (bytes).",          "read_file(${1:path})"),
        fn("write_file",  "io.write_file(path, content) -> null",  "Overwrite the file at path.",                  "write_file(${1:path}, ${2:content})"),
        fn("append_file", "io.append_file(path, content) -> null", "Append; creates the file if missing.",         "append_file(${1:path}, ${2:content})"),
        fn("exists",      "io.exists(path) -> bool",               "Whether the path exists.",                     "exists(${1:path})"),
        fn("is_file",     "io.is_file(path) -> bool",              "Whether path exists and is a regular file.",   "is_file(${1:path})"),
        fn("is_dir",      "io.is_dir(path) -> bool",               "Whether path exists and is a directory.",      "is_dir(${1:path})"),
        fn("stat",        "io.stat(path) -> map",                  "Returns {bytes, mtime, is_file, is_dir}.",     "stat(${1:path})"),
        fn("mkdir",       "io.mkdir(path) -> null",                "Recursive mkdir (-p semantics).",              "mkdir(${1:path})"),
        fn("list_dir",    "io.list_dir(path) -> list",             "Entry names (no '.' / '..').",                 "list_dir(${1:path})"),
        fn("remove",      "io.remove(path) -> null",               "Recursive remove; idempotent.",                "remove(${1:path})"),
        fn("rename",      "io.rename(from, to) -> null",           "Rename / move.",                               "rename(${1:from}, ${2:to})"),
        fn("copy_file",   "io.copy_file(from, to) -> null",        "Copy a single regular file.",                  "copy_file(${1:from}, ${2:to})"),
        // async
        fn("read_file_async",  "io.read_file_async(path, cb) -> null",        "cb(err, data) on completion.",      "read_file_async(${1:path}, function (err, data) { ${0} })"),
        fn("write_file_async", "io.write_file_async(path, content, cb) -> null", "cb(err) on completion.",         "write_file_async(${1:path}, ${2:content}, function (err) { ${0} })"),
        fn("open_read",        "io.open_read(path) -> stream",                "Pull-based read stream {read(n,cb), close()}.", "open_read(${1:path})"),
        fn("open_write",       "io.open_write(path) -> stream",               "Pull-based write stream {write(d,cb), close()}.", "open_write(${1:path})"),
    ],

    timers: [
        fn("set",      "timers.set(ms, fn) -> cancel",      "One-shot timer. Returns a 0-arg cancel callable.", "set(${1:ms}, function () { ${0} })"),
        fn("interval", "timers.interval(ms, fn) -> cancel", "Repeating timer.",                                  "interval(${1:ms}, function () { ${0} })"),
    ],

    time: [
        fn("now",             "time.now() -> number",                 "Milliseconds since the Unix epoch.",                                                                       "now()"),
        fn("now_seconds",     "time.now_seconds() -> number",         "Seconds since the Unix epoch.",                                                                            "now_seconds()"),
        fn("now_ns",          "time.now_ns() -> number",              "Nanoseconds since the Unix epoch.",                                                                        "now_ns()"),
        fn("components",      "time.components(ms, local?) -> map",   "Decompose `ms` into {year, month, day, hour, minute, second, ms}. Pass `local=true` for local timezone.", "components(${1:ms}, ${2:false})"),
        fn("from",            "time.from(parts, local?) -> number",   "Build a millisecond timestamp from a components map.",                                                     "from(${1:parts}, ${2:false})"),
        fn("local_offset_ms", "time.local_offset_ms(ms) -> number",   "Local-timezone offset in ms (positive east of UTC).",                                                      "local_offset_ms(${1:ms})"),
        fn("seconds",         "time.seconds(n) -> number",            "`n` seconds expressed in milliseconds.",                                                                   "seconds(${1:n})"),
        fn("minutes",         "time.minutes(n) -> number",            "`n` minutes expressed in milliseconds.",                                                                   "minutes(${1:n})"),
        fn("hours",           "time.hours(n) -> number",              "`n` hours expressed in milliseconds.",                                                                     "hours(${1:n})"),
        fn("days",            "time.days(n) -> number",               "`n` days expressed in milliseconds.",                                                                      "days(${1:n})"),
        fn("add_seconds",     "time.add_seconds(ms, n) -> number",    "Add `n` seconds to a millisecond timestamp.",                                                              "add_seconds(${1:ms}, ${2:n})"),
        fn("add_minutes",     "time.add_minutes(ms, n) -> number",    "Add `n` minutes to a millisecond timestamp.",                                                              "add_minutes(${1:ms}, ${2:n})"),
        fn("add_hours",       "time.add_hours(ms, n) -> number",      "Add `n` hours to a millisecond timestamp.",                                                                "add_hours(${1:ms}, ${2:n})"),
        fn("add_days",        "time.add_days(ms, n) -> number",       "Add `n` days to a millisecond timestamp.",                                                                 "add_days(${1:ms}, ${2:n})"),
        fn("iso",             "time.iso(ms) -> string",               "ISO 8601 UTC string with millisecond precision (suffix `Z`).",                                             "iso(${1:ms})"),
        fn("iso_local",       "time.iso_local(ms) -> string",         "ISO 8601 local-timezone string with millisecond precision.",                                               "iso_local(${1:ms})"),
        fn("parse_iso",       "time.parse_iso(s) -> number",          "Parse an ISO 8601 string into milliseconds since epoch.",                                                  "parse_iso(${1:s})"),
    ],

    url: [
        fn("parse",       "url.parse(s) -> map",              "Parse a URL into {scheme, host, port, path, query, fragment}.",                                                    "parse(${1:s})"),
        fn("encode",      "url.encode(s) -> string",          "Percent-encode a string per RFC 3986 (unreserved set).",                                                           "encode(${1:s})"),
        fn("decode",      "url.decode(s) -> string",          "Percent-decode a string. `+` is decoded as space.",                                                                "decode(${1:s})"),
        fn("build_query", "url.build_query(params) -> string", "Build a `k=v&k=v` query string from a map (values are URL-encoded; null values become empty).",                  "build_query(${1:params})"),
        fn("parse_query", "url.parse_query(s) -> map",        "Parse a `k=v&k=v` query string into a map.",                                                                       "parse_query(${1:s})"),
    ],

    path: [
        fn("sep",         "path.sep: string",                "Platform-aware separator: '/' on POSIX, '\\\\' on Windows."),
        fn("is_absolute", "path.is_absolute(p) -> bool",     "Whether `p` is absolute (POSIX `/foo` or Windows `C:\\foo`).",   "is_absolute(${1:p})"),
        fn("dirname",     "path.dirname(p) -> string",       "Directory portion of `p`. Empty input → '.'.",                    "dirname(${1:p})"),
        fn("basename",    "path.basename(p) -> string",      "Final segment of `p`.",                                           "basename(${1:p})"),
        fn("stem",        "path.stem(p) -> string",          "`basename(p)` without its extension.",                            "stem(${1:p})"),
        fn("extname",     "path.extname(p) -> string",       "Extension of `p` including the leading dot, or '' if none.",     "extname(${1:p})"),
        fn("join",        "path.join(parts) -> string",      "Join path segments with '/'. Trims redundant separators.",       "join(${1:parts})"),
        fn("normalize",   "path.normalize(p) -> string",     "Normalize `.` / `..` segments. Empty paths return '.'.",         "normalize(${1:p})"),
    ],

    math: [
        // constants
        fn("pi",         "math.pi: number",                  "π ≈ 3.14159…"),
        fn("e",          "math.e: number",                   "e ≈ 2.71828…"),
        fn("inf",        "math.inf: number",                 "Positive infinity."),
        fn("nan",        "math.nan: number",                 "Not-a-number."),
        // basic
        fn("sqrt",       "math.sqrt(x) -> number",           "Square root.",                       "sqrt(${1:x})"),
        fn("exp",        "math.exp(x) -> number",            "e raised to x.",                     "exp(${1:x})"),
        fn("log",        "math.log(x) -> number",            "Natural logarithm.",                 "log(${1:x})"),
        fn("log2",       "math.log2(x) -> number",           "Base-2 logarithm.",                  "log2(${1:x})"),
        fn("log10",      "math.log10(x) -> number",          "Base-10 logarithm.",                 "log10(${1:x})"),
        // trig
        fn("sin",        "math.sin(x) -> number",            "Sine (radians).",                    "sin(${1:x})"),
        fn("cos",        "math.cos(x) -> number",            "Cosine (radians).",                  "cos(${1:x})"),
        fn("tan",        "math.tan(x) -> number",            "Tangent (radians).",                 "tan(${1:x})"),
        fn("asin",       "math.asin(x) -> number",           "Arcsine (radians).",                 "asin(${1:x})"),
        fn("acos",       "math.acos(x) -> number",           "Arccosine (radians).",               "acos(${1:x})"),
        fn("atan",       "math.atan(x) -> number",           "Arctangent (radians).",              "atan(${1:x})"),
        fn("atan2",      "math.atan2(y, x) -> number",       "Two-argument arctangent.",           "atan2(${1:y}, ${2:x})"),
        fn("pow",        "math.pow(x, y) -> number",         "x raised to y.",                     "pow(${1:x}, ${2:y})"),
        // rounding / abs
        fn("floor",      "math.floor(x) -> number",          "Greatest integer ≤ x.",              "floor(${1:x})"),
        fn("ceil",       "math.ceil(x) -> number",           "Smallest integer ≥ x.",              "ceil(${1:x})"),
        fn("round",      "math.round(x) -> number",          "Nearest integer.",                   "round(${1:x})"),
        fn("trunc",      "math.trunc(x) -> number",          "Truncate toward zero.",              "trunc(${1:x})"),
        fn("abs",        "math.abs(x) -> number",            "Absolute value.",                    "abs(${1:x})"),
        // predicates
        fn("is_nan",     "math.is_nan(x) -> bool",           "True if x is NaN.",                  "is_nan(${1:x})"),
        fn("is_finite",  "math.is_finite(x) -> bool",        "True if x is finite (not NaN / ±Inf).", "is_finite(${1:x})"),
        // misc
        fn("sign",       "math.sign(x) -> number",           "1 if x>0, -1 if x<0, 0 otherwise.",  "sign(${1:x})"),
        fn("min",        "math.min(a, b) -> number",         "Smaller of two values.",             "min(${1:a}, ${2:b})"),
        fn("max",        "math.max(a, b) -> number",         "Larger of two values.",              "max(${1:a}, ${2:b})"),
        fn("clamp",      "math.clamp(x, lo, hi) -> number",  "Clamp x to [lo, hi].",               "clamp(${1:x}, ${2:lo}, ${3:hi})"),
        fn("lerp",       "math.lerp(a, b, t) -> number",     "Linear interpolation a + (b-a)*t.",  "lerp(${1:a}, ${2:b}, ${3:t})"),
        fn("to_radians", "math.to_radians(deg) -> number",   "Convert degrees to radians.",        "to_radians(${1:deg})"),
        fn("to_degrees", "math.to_degrees(rad) -> number",   "Convert radians to degrees.",        "to_degrees(${1:rad})"),
        fn("mod",        "math.mod(a, b) -> number",         "Modulo with non-negative result.",   "mod(${1:a}, ${2:b})"),
        fn("sum",        "math.sum(xs) -> number",           "Sum of all elements in a list.",     "sum(${1:xs})"),
        fn("product",    "math.product(xs) -> number",       "Product of all elements in a list.", "product(${1:xs})"),
        fn("mean",       "math.mean(xs) -> number",          "Arithmetic mean. nan for empty.",    "mean(${1:xs})"),
    ],

    json: [
        fn("parse",     "json.parse(s) -> any",                     "Parse a JSON string. Returns null and prints to stderr on malformed input.", "parse(${1:s})"),
        fn("stringify", "json.stringify(value, indent?) -> string", "Serialize to JSON. `indent` is 0..16 (0 = single-line compact, default).",    "stringify(${1:value}, ${2:0})"),
    ],

    log: [
        // levels (numeric constants)
        fn("DEBUG",         "log.DEBUG: number = 10"),
        fn("INFO",          "log.INFO: number = 20"),
        fn("WARN",          "log.WARN: number = 30"),
        fn("ERROR",         "log.ERROR: number = 40"),
        // config
        fn("set_level",     "log.set_level(level) -> null",   "Set the minimum level. Accepts 'debug'/'info'/'warn'/'error' or a number.", "set_level(${1:\"info\"})"),
        fn("set_formatter", "log.set_formatter(fn) -> null",  "Override the formatter `(num, name, msg) -> string`.",                       "set_formatter(${1:fn})"),
        fn("set_sink",      "log.set_sink(fn) -> null",       "Override the sink `(formatted) -> any`. Default writes via print.",         "set_sink(${1:fn})"),
        // emit
        fn("debug",         "log.debug(msg) -> null",         "Emit at DEBUG level.",                                                       "debug(${1:msg})"),
        fn("info",          "log.info(msg) -> null",          "Emit at INFO level.",                                                        "info(${1:msg})"),
        fn("warn",          "log.warn(msg) -> null",          "Emit at WARN level.",                                                        "warn(${1:msg})"),
        fn("error",         "log.error(msg) -> null",         "Emit at ERROR level.",                                                       "error(${1:msg})"),
    ],

    exec: [
        fn("spawn",
            "exec.spawn(cmd, args, opts, on_exit) -> process",
            "Low-level: launch `cmd` with `args`. Returns a process handle with `.stdin`, `.stdout`, `.stderr` streams. `on_exit(code, signal)` fires when the child exits.",
            "spawn(${1:cmd}, ${2:args}, ${3:{}}, function (code, sig) { ${0} })"),
        fn("run",
            "exec.run(cmd, args, cb) -> process",
            "High-level: spawn, buffer stdout/stderr, close stdin, and fire `cb(err, {code, signal, stdout, stderr})` when done.",
            "run(${1:cmd}, ${2:args}, function (err, res) { ${0} })"),
        fn("run_with_input",
            "exec.run_with_input(cmd, args, input, cb) -> process",
            "Same as `run` but writes `input` to the child's stdin before closing it.",
            "run_with_input(${1:cmd}, ${2:args}, ${3:input}, function (err, res) { ${0} })"),
    ],

    random: [
        fn("seed",        "random.seed(n) -> null",          "Seed the PRNG. Same seed → same sequence.",                  "seed(${1:n})"),
        fn("next",        "random.next() -> number",         "Float in [0, 1).",                                            "next()"),
        fn("bytes",       "random.bytes(n) -> string",       "n raw random bytes (PRNG, not crypto-safe — use `crypto.random_bytes` for tokens).", "bytes(${1:n})"),
        fn("int",         "random.int(min, max) -> number",  "Integer in [min, max] inclusive.",                            "int(${1:min}, ${2:max})"),
        fn("float",       "random.float() -> number",        "Float in [0, 1). Alias for `next`.",                          "float()"),
        fn("range",       "random.range(lo, hi) -> number",  "Float in [lo, hi).",                                          "range(${1:lo}, ${2:hi})"),
        fn("bool",        "random.bool() -> bool",           "True or false with probability 0.5 each.",                    "bool()"),
        fn("probability", "random.probability(p) -> bool",   "True with probability `p` ∈ [0, 1].",                         "probability(${1:p})"),
        fn("choice",      "random.choice(xs) -> any",        "Pick one element uniformly. Throws if `xs` is empty.",        "choice(${1:xs})"),
        fn("shuffle",     "random.shuffle(xs) -> list",      "Fisher–Yates in place. Returns the same list for chaining.",  "shuffle(${1:xs})"),
        fn("sample",      "random.sample(xs, k) -> list",    "k distinct elements without replacement. Throws if k>len.",    "sample(${1:xs}, ${2:k})"),
    ],

    uuid: [
        fn("v4",       "uuid.v4() -> string",       "Generate a random (RFC 4122 v4) UUID as a 36-char canonical string.", "v4()"),
        fn("nil",      "uuid.nil() -> string",      "The nil UUID: '00000000-0000-0000-0000-000000000000'.",                "nil()"),
        fn("is_valid", "uuid.is_valid(s) -> bool",  "Whether `s` is a 36-char canonical hex-and-dashes UUID.",              "is_valid(${1:s})"),
        fn("is_v4",    "uuid.is_v4(s) -> bool",     "Whether `s` is a valid UUID with version field set to 4.",             "is_v4(${1:s})"),
    ],

    crypto: [
        fn("random_bytes",  "crypto.random_bytes(n) -> string",          "n cryptographic-random bytes as a raw byte string.",                              "random_bytes(${1:n})"),
        fn("random_hex",    "crypto.random_hex(n) -> string",            "n random bytes as 2n lowercase hex chars.",                                       "random_hex(${1:n})"),
        fn("hash",          "crypto.hash(algo, data) -> string",         "Hex digest. `algo`: md5, sha1, sha224, sha256, sha384, sha512.",                  "hash(${1:\"sha256\"}, ${2:data})"),
        fn("hmac",          "crypto.hmac(algo, key, data) -> string",    "Hex HMAC tag.",                                                                    "hmac(${1:\"sha256\"}, ${2:key}, ${3:data})"),
        fn("b64_encode",    "crypto.b64_encode(data) -> string",         "Standard base64 with `=` padding (single line).",                                 "b64_encode(${1:data})"),
        fn("b64_decode",    "crypto.b64_decode(data) -> string",         "Raw bytes from standard base64.",                                                  "b64_decode(${1:data})"),
        fn("b64url_encode", "crypto.b64url_encode(data) -> string",      "URL-safe base64 (`-` `_`), no padding. The encoding JWTs use.",                  "b64url_encode(${1:data})"),
        fn("b64url_decode", "crypto.b64url_decode(data) -> string",      "URL-safe base64 decode. Padding optional.",                                        "b64url_decode(${1:data})"),
        fn("hex_encode",    "crypto.hex_encode(data) -> string",         "Lowercase hex of raw bytes.",                                                      "hex_encode(${1:data})"),
        fn("hex_decode",    "crypto.hex_decode(data) -> string",         "Raw bytes from hex (case-insensitive).",                                           "hex_decode(${1:data})"),
        fn("equals",        "crypto.equals(a, b) -> bool",               "Constant-time string compare. Use this for HMAC / token checks to defeat timing side channels.", "equals(${1:a}, ${2:b})"),
    ],

    csv: [
        fn("parse",
           "csv.parse(text) -> list<list<string>>",
           "Parse CSV text into a list of rows. Handles quoted fields and embedded quotes/newlines (RFC 4180 dialect).",
           "parse(${1:text})"),
        fn("parse_records",
           "csv.parse_records(text) -> list<map>",
           "Like `parse` but treats the first row as headers and returns each subsequent row as a `{header: value}` map.",
           "parse_records(${1:text})"),
        fn("stringify",
           "csv.stringify(rows) -> string",
           "Serialize a list of rows back to CSV text. Fields needing quoting are quoted automatically.",
           "stringify(${1:rows})"),
    ],

    cookie: [
        fn("parse",   "cookie.parse(header) -> map",                  "Parse a `Cookie:` header value into a `{name: value}` map.",     "parse(${1:header})"),
        fn("build",   "cookie.build(name, value, opts?) -> string",   "Build a Set-Cookie line. `opts` may contain path, domain, max_age, expires, http_only, secure, same_site.", "build(${1:name}, ${2:value}, ${3:opts})"),
        fn("delete_", "cookie.delete_(name, opts?) -> string",        "Build a Set-Cookie that expires immediately (deletes the cookie). Note the trailing `_` — `delete` is a reserved keyword.", "delete_(${1:name})"),
    ],

    session: [
        fn("create_store",
           "session.create_store(opts?) -> store",
           "Create an in-memory session store. `opts`: {cookie_name (default 'bnl_sid'), max_age (86400), same_site ('Lax'), secure (false)}. Returned store has `.before`, `.after`, `.destroy`, `.count`, `.cookie_name` — register `.before` / `.after` on a `web.app()` instance.",
           "create_store(${1:opts})"),
    ],

    net: [
        fn("tcp_listen",
           "net.tcp_listen(port, on_conn) -> listener",
           "Open a TCP listener on `port`. `on_conn(conn)` fires for each accepted connection. The conn has `.write(d, cb?)`, `.on_data(fn)`, `.on_end(fn)`, `.close()`.",
           "tcp_listen(${1:port}, function (conn) { ${0} })"),
        fn("tcp_connect",
           "net.tcp_connect(ip, port, cb) -> null",
           "Connect to `ip:port`. `cb(err, conn)` fires with the connection or an error.",
           "tcp_connect(${1:ip}, ${2:port}, function (err, conn) { ${0} })"),
        fn("resolve",
           "net.resolve(host, cb) -> null",
           "Resolve `host` (DNS A/AAAA). `cb(err, ip)` fires with the first address found.",
           "resolve(${1:host}, function (err, ip) { ${0} })"),
    ],

    http: [
        fn("parse_request",
           "http.parse_request(text) -> map",
           "Parse an HTTP/1.x request. Returns {complete, consumed, method, url, version, headers, body, ...}.",
           "parse_request(${1:text})"),
        fn("parse_response",
           "http.parse_response(text, ended?) -> map",
           "Parse an HTTP/1.x response. Pass `ended=true` to allow body-runs-to-close.",
           "parse_response(${1:text}, ${2:false})"),
    ],

    tls: [
        fn("connect",
           "tls.connect(host, ip, port, cb, opts?) -> null",
           "TLS-wrap a TCP connection to `ip:port`, validating the cert against `host`. `cb(err, conn)` gives a stream identical to a `net` conn.",
           "connect(${1:host}, ${2:ip}, ${3:port}, function (err, conn) { ${0} })"),
        fn("listen",
           "tls.listen(port, opts, on_conn) -> listener",
           "Open a TLS listener. `opts` must include {cert, key} (paths or PEM strings). Each accepted conn behaves like a `net` conn.",
           "listen(${1:port}, ${2:opts}, function (conn) { ${0} })"),
    ],

    regex: [
        fn("test",
           "regex.test(pattern, str, flags?) -> bool",
           "True if `pattern` matches anywhere in `str`. `flags`: 'i' / 'm' / 's' (combinable).",
           "test(${1:pattern}, ${2:str})"),
        fn("match",
           "regex.match(pattern, str, flags?) -> map | null",
           "First match as `{match, groups, index}`, or null if no match. Unmatched groups are null.",
           "match(${1:pattern}, ${2:str})"),
        fn("match_all",
           "regex.match_all(pattern, str, flags?) -> list<map>",
           "Every match as a list of `{match, groups, index}` maps. Empty list if no matches.",
           "match_all(${1:pattern}, ${2:str})"),
        fn("replace",
           "regex.replace(pattern, str, repl, flags?) -> string",
           "Replace ALL matches. `repl` supports backrefs: $1..$9, $& (whole match), $$ (literal $).",
           "replace(${1:pattern}, ${2:str}, ${3:repl})"),
        fn("replace_first",
           "regex.replace_first(pattern, str, repl, flags?) -> string",
           "Replace only the first match.",
           "replace_first(${1:pattern}, ${2:str}, ${3:repl})"),
        fn("split",
           "regex.split(pattern, str, flags?) -> list<string>",
           "Split `str` at each match. Adjacent matches yield empty-string entries.",
           "split(${1:pattern}, ${2:str})"),
        fn("escape",
           "regex.escape(str) -> string",
           "Escape every regex metacharacter so the result matches `str` literally.",
           "escape(${1:str})"),
    ],

    zlib: [
        fn("version",    "zlib.version() -> string",                    "Underlying zlib version.",                                   "version()"),
        fn("gzip",       "zlib.gzip(data) -> string",                   "Gzip-compress `data` at the default level.",                  "gzip(${1:data})"),
        fn("gzip_at",    "zlib.gzip_at(data, level) -> string",         "Gzip-compress at a specific level (0–9, or -1 for default).", "gzip_at(${1:data}, ${2:level})"),
        fn("gunzip",     "zlib.gunzip(data) -> string",                 "Gzip-decompress.",                                            "gunzip(${1:data})"),
        fn("deflate",    "zlib.deflate(data) -> string",                "Raw deflate at default level (no gzip header).",              "deflate(${1:data})"),
        fn("deflate_at", "zlib.deflate_at(data, level) -> string",      "Raw deflate at a specific level.",                            "deflate_at(${1:data}, ${2:level})"),
        fn("inflate",    "zlib.inflate(data) -> string",                "Raw inflate.",                                                "inflate(${1:data})"),
    ],

    dns: [
        fn("lookup",         "dns.lookup(host, family, cb) -> null",         "Resolve `host` to one IP. `family`: 0 = any, 4 = IPv4, 6 = IPv6. `cb(err, ip, version)`.", "lookup(${1:host}, ${2:0}, function (err, ip, ver) { ${0} })"),
        fn("lookup_all",     "dns.lookup_all(host, family, cb) -> null",     "Resolve `host` to a list of IPs. `cb(err, ips)`.",                                          "lookup_all(${1:host}, ${2:0}, function (err, ips) { ${0} })"),
        fn("reverse",        "dns.reverse(ip, cb) -> null",                  "Reverse-DNS an IP. `cb(err, names)`.",                                                      "reverse(${1:ip}, function (err, names) { ${0} })"),
        fn("is_ipv4",        "dns.is_ipv4(s) -> bool",                       "Whether `s` is a dotted-quad IPv4 literal.",                                                "is_ipv4(${1:s})"),
        fn("is_ipv6",        "dns.is_ipv6(s) -> bool",                       "Whether `s` is an IPv6 literal.",                                                            "is_ipv6(${1:s})"),
        fn("is_ip",          "dns.is_ip(s) -> bool",                         "True if `s` is any IP literal.",                                                             "is_ip(${1:s})"),
        fn("lookup_or_self", "dns.lookup_or_self(host, cb) -> null",         "If `host` is already an IP literal, call `cb` synchronously; otherwise `dns.lookup`.",      "lookup_or_self(${1:host}, function (err, ip, ver) { ${0} })"),
    ],

    template: [
        fn("set_views",       "template.set_views(dir) -> null",                "Set the directory used by `render(path, ctx)`.",                                "set_views(${1:dir})"),
        fn("clear_cache",     "template.clear_cache() -> null",                 "Clear the compiled-template cache.",                                            "clear_cache()"),
        fn("register_filter", "template.register_filter(name, fn) -> null",     "Add a filter callable as `{{ value | name(args) }}`. `fn(v, args) -> any`.",   "register_filter(${1:name}, ${2:fn})"),
        fn("render",
           "template.render(path, ctx?) -> string",
           "Render the file at `<views_dir>/<path>` with `ctx`. Supports `{{ expr | filter }}`, `{% if %} {% else %} {% end %}`, `{% for x in xs %} {% end %}`, `{% include \"name\" %}`, `{% extends \"name\" %}` + `{% block name %} {% end %}`. Use `{{= raw }}` to bypass HTML-escape.",
           "render(${1:path}, ${2:ctx})"),
        fn("render_string",   "template.render_string(text, ctx?) -> string",   "Same as `render`, but the template body is given as a string.",                "render_string(${1:text}, ${2:ctx})"),
    ],

    multipart: [
        fn("generate_boundary",
           "multipart.generate_boundary() -> string",
           "Generate a fresh `----bnlBoundary<hex>` boundary marker.",
           "generate_boundary()"),
        fn("encode",
           "multipart.encode(parts, boundary) -> string",
           "Serialize a list of parts into a multipart body. Each part: `{name, filename?, content_type?, body | value}`.",
           "encode(${1:parts}, ${2:boundary})"),
        fn("decode",
           "multipart.decode(body, boundary) -> list<map>",
           "Parse a multipart body into a list of `{name, filename, content_type, body, headers}` parts.",
           "decode(${1:body}, ${2:boundary})"),
        fn("streaming_decode",
           "multipart.streaming_decode(boundary, on_part_start, on_part_chunk, on_part_end) -> {feed, end}",
           "Streaming parser. Call `.feed(chunk)` as bytes arrive and `.end()` at EOF.",
           "streaming_decode(${1:boundary}, function (p) { ${0} }, function (chunk) {}, function () {})"),
        fn("build_field_part",
           "multipart.build_field_part(boundary, name, value) -> string",
           "Serialize a single form-field part (no file).",
           "build_field_part(${1:boundary}, ${2:name}, ${3:value})"),
        fn("build_file_preamble",
           "multipart.build_file_preamble(boundary, name, filename, content_type) -> string",
           "Serialize a file part's headers (no body). For streaming uploads.",
           "build_file_preamble(${1:boundary}, ${2:name}, ${3:filename}, ${4:content_type})"),
        fn("build_epilogue",
           "multipart.build_epilogue(boundary) -> string",
           "The closing `--boundary--` line of a multipart body.",
           "build_epilogue(${1:boundary})"),
    ],

    dotenv: [
        fn("parse",
           "dotenv.parse(text) -> map",
           "Parse `KEY=value` lines into a map. Strips comments, supports `export KEY=...`, and unquotes `\"...\"` / `'...'`.",
           "parse(${1:text})"),
        fn("load",
           "dotenv.load(path) -> map",
           "Read a file and `parse` it. Throws if the file is missing.",
           "load(${1:path})"),
        fn("load_or_empty",
           "dotenv.load_or_empty(path) -> map",
           "Like `load`, but returns `{}` if the file doesn't exist.",
           "load_or_empty(${1:path})"),
    ],

    cli: [
        fn("parser",
           "cli.parser(name) -> parser",
           "Create a parser with empty flags / options / positionals tables. Chain `flag` / `option` / `positional` calls on it.",
           "parser(${1:\"prog\"})"),
        fn("flag",
           "cli.flag(p, spec) -> parser",
           "Add a boolean flag. `spec`: `{name, short?, help?}`. Default value is `false`.",
           "flag(${1:p}, {name: ${2:\"verbose\"}, short: \"v\"})"),
        fn("option",
           "cli.option(p, spec) -> parser",
           "Add an option that takes a value. `spec`: `{name, short?, help?, default?}`.",
           "option(${1:p}, {name: ${2:\"output\"}, short: \"o\", default: \"-\"})"),
        fn("positional",
           "cli.positional(p, spec) -> parser",
           "Add a positional argument. `spec`: `{name, help?, default?}`.",
           "positional(${1:p}, {name: ${2:\"input\"}})"),
        fn("parse",
           "cli.parse(p) -> map",
           "Parse the actual process argv. Returns `{<name>: value, ..., _rest: [unmatched]}`. Throws on unknown options.",
           "parse(${1:p})"),
        fn("parse_argv",
           "cli.parse_argv(p, argv) -> map",
           "Like `parse`, but with an explicit `argv` list (useful for tests).",
           "parse_argv(${1:p}, ${2:argv})"),
        fn("usage",
           "cli.usage(p) -> string",
           "Build a `usage: ...` help string from a parser.",
           "usage(${1:p})"),
    ],

    test: [
        fn("test",
           "test.test(name, fn) -> null",
           "Register a test. `fn()` is called by `test.run()`; throw anything to fail.",
           "test(${1:\"name\"}, function () { ${0} })"),
        // assertions
        fn("equal",         "test.equal(actual, expected) -> null",          "Assert `actual == expected`.",                                 "equal(${1:actual}, ${2:expected})"),
        fn("not_equal",     "test.not_equal(actual, expected) -> null",      "Assert `actual != expected`.",                                 "not_equal(${1:actual}, ${2:expected})"),
        fn("is_true",       "test.is_true(v) -> null",                       "Assert `v` is the value `true`.",                              "is_true(${1:v})"),
        fn("is_false",      "test.is_false(v) -> null",                      "Assert `v` is the value `false`.",                             "is_false(${1:v})"),
        fn("is_null",       "test.is_null(v) -> null",                       "Assert `v == null`.",                                          "is_null(${1:v})"),
        fn("not_null",      "test.not_null(v) -> null",                      "Assert `v != null`.",                                          "not_null(${1:v})"),
        fn("contains",      "test.contains(haystack, needle) -> null",       "Assert that a string contains a substring, or a list contains an element.", "contains(${1:haystack}, ${2:needle})"),
        fn("throws",        "test.throws(fn) -> null",                       "Assert that `fn()` throws anything.",                          "throws(function () { ${0} })"),
        fn("throws_with",   "test.throws_with(fn, message_substring) -> null", "Assert that `fn()` throws and the message includes `message_substring`.", "throws_with(function () { ${1} }, ${2:\"substr\"})"),
        // runner
        fn("run",
           "test.run() -> null",
           "Run all registered tests, print pass/fail per test plus a summary line, and `sys.exit(1)` if any failed.",
           "run()"),
    ],

    ws: [
        fn("WS_GUID",          "ws.WS_GUID: string",                          "The WebSocket GUID per RFC 6455 (used in the accept-key hash)."),
        fn("validate_request", "ws.validate_request(req) -> bool",            "Whether `req` is a well-formed WebSocket upgrade.",                "validate_request(${1:req})"),
        fn("accept",
           "ws.accept(conn, req) -> ws_conn",
           "Complete the WebSocket handshake on `conn`. Returns an API with `.on_message(fn) / .on_close(fn) / .on_ping(fn)`, `.send(text) / .send_binary(data) / .ping(data) / .close(code, reason)`.",
           "accept(${1:conn}, ${2:req})"),
    ],

    pg: [
        fn("version",
           "pg.version() -> string",
           "Underlying libpq version.",
           "version()"),
        fn("connect",
           "pg.connect(conninfo_or_opts) -> db",
           "Open a PostgreSQL connection. Pass either a libpq conninfo string or an options map (which is serialized to conninfo).",
           "connect(${1:conninfo_or_opts})"),
        fn("transaction",
           "pg.transaction(db, fn) -> any",
           "Run `fn(db)` inside BEGIN/COMMIT. Rolls back and re-throws if `fn` throws.",
           "transaction(${1:db}, function (db) { ${0} })"),
        fn("migrate",
           "pg.migrate(db, statements) -> number",
           "Execute a list of SQL statements inside a single transaction. Returns the count.",
           "migrate(${1:db}, ${2:statements})"),
        fn("insert",
           "pg.insert(db, table, row) -> map",
           "Convenience INSERT ... RETURNING * from a row map. Returns the inserted row as a map.",
           "insert(${1:db}, ${2:table}, ${3:row})"),
    ],

    sqlite: [
        fn("open",
           "sqlite.open(path) -> db",
           "Open (or create) a SQLite database file.",
           "open(${1:path})"),
        fn("version",
           "sqlite.version() -> string",
           "Underlying SQLite version.",
           "version()"),
        fn("transaction",
           "sqlite.transaction(db, fn) -> any",
           "Run `fn(db)` inside BEGIN/COMMIT. Rolls back and re-throws if `fn` throws.",
           "transaction(${1:db}, function (db) { ${0} })"),
        fn("migrate",
           "sqlite.migrate(db, statements) -> number",
           "Execute a list of SQL statements inside a single transaction. Returns the count.",
           "migrate(${1:db}, ${2:statements})"),
        fn("insert",
           "sqlite.insert(db, table, row) -> number",
           "Convenience INSERT from a row map. Returns the last insert id.",
           "insert(${1:db}, ${2:table}, ${3:row})"),
    ],

    mongo: [
        fn("version",
           "mongo.version() -> string",
           "Underlying MongoDB driver version.",
           "version()"),
        fn("connect",
           "mongo.connect(uri) -> client",
           "Open a MongoDB connection from a `mongodb://...` URI.",
           "connect(${1:uri})"),
    ],

    request: [
        // default-instance verb shortcuts
        fn("request",   "request.request(config) -> Future<response>",        "Send a request using the default instance.",                                       "request(${1:config})"),
        fn("get",       "request.get(url, config?) -> Future<response>",      "GET. `config` may include headers, params, timeout, base_url, tls, pool.",         "get(${1:url})"),
        fn("head",      "request.head(url, config?) -> Future<response>",     "HEAD.",                                                                            "head(${1:url})"),
        fn("delete",    "request.delete(url, config?) -> Future<response>",   "DELETE.",                                                                          "delete(${1:url})"),
        fn("post",      "request.post(url, data, config?) -> Future<response>",  "POST. `data` is JSON-encoded if a map/list, sent raw if a string.",            "post(${1:url}, ${2:data})"),
        fn("put",       "request.put(url, data, config?) -> Future<response>",   "PUT.",                                                                          "put(${1:url}, ${2:data})"),
        fn("patch",     "request.patch(url, data, config?) -> Future<response>", "PATCH.",                                                                        "patch(${1:url}, ${2:data})"),
        fn("post_form", "request.post_form(url, fields, config?) -> Future<response>",
                       "POST application/x-www-form-urlencoded.",                                                                                                  "post_form(${1:url}, ${2:fields})"),

        // bulk transfers
        fn("download",  "request.download(url, dest, config?) -> Future<response>",
                       "Stream a GET response body to a file at `dest`. `config.on_progress(bytes)` fires per chunk if supplied.",
                       "download(${1:url}, ${2:dest})"),
        fn("upload",    "request.upload(url, file, config?) -> Future<response>",
                       "Send a multipart/form-data upload. `file` is a path string or {path, name, filename, content_type}. `config.fields` adds extra form fields.",
                       "upload(${1:url}, ${2:file})"),

        // default-instance hooks
        fn("before", "request.before(fn) -> null", "Register a before-request hook on the default instance. `fn(config)` may return a modified config.", "before(${1:fn})"),
        fn("after",  "request.after(fn) -> null",  "Register an after-response hook on the default instance. `fn(resp)` may return a modified response.", "after(${1:fn})"),

        // instances & pool
        fn("create",   "request.create(defaults?) -> instance", "Create an isolated instance with its own defaults and hooks (`.get`/`.post`/...).", "create(${1:defaults})"),
        fn("shutdown", "request.shutdown() -> null", "Close every connection in the keep-alive pool. Call before exit.", "shutdown()"),
    ],

    mysql: [
        fn("version",
           "mysql.version() -> string",
           "Underlying MySQL client library version.",
           "version()"),
        fn("connect",
           "mysql.connect(url_or_opts) -> db",
           "Open a MySQL connection. Pass either a `mysql://user:pass@host:port/db?...` URL string or an options map.",
           "connect(${1:url_or_opts})"),
        fn("parse_url",
           "mysql.parse_url(url) -> map",
           "Parse a `mysql://...` URL into the options map accepted by `connect`.",
           "parse_url(${1:url})"),
        fn("transaction",
           "mysql.transaction(db, fn) -> any",
           "Run `fn(db)` inside BEGIN/COMMIT. Rolls back and re-throws if `fn` throws.",
           "transaction(${1:db}, function (db) { ${0} })"),
        fn("migrate",
           "mysql.migrate(db, statements) -> number",
           "Execute a list of SQL statements inside a single transaction. Returns the count.",
           "migrate(${1:db}, ${2:statements})"),
        fn("insert",
           "mysql.insert(db, table, row) -> number",
           "Convenience INSERT from a row map. Returns the last insert id.",
           "insert(${1:db}, ${2:table}, ${3:row})"),
    ],

    web: [
        // tunables
        fn("DEFAULT_IDLE_TIMEOUT_MS", "web.DEFAULT_IDLE_TIMEOUT_MS: number = 30000",
           "Default idle timeout (ms) before closing a kept-alive connection."),
        fn("DEFAULT_MAX_BODY_SIZE",   "web.DEFAULT_MAX_BODY_SIZE: number = 10485760",
           "Default request body cap (bytes)."),

        // response builders
        fn("text",     "web.text(s) -> response",            "200 plain-text response.",                                                 "text(${1:s})"),
        fn("html",     "web.html(s) -> response",            "200 text/html response.",                                                  "html(${1:s})"),
        fn("json",     "web.json(value) -> response",        "200 application/json response (value is JSON-stringified).",               "json(${1:value})"),
        fn("redirect", "web.redirect(url) -> response",      "302 redirect to `url`.",                                                   "redirect(${1:url})"),
        fn("error",    "web.error(status, msg?) -> response", "Error response. `msg` defaults to the standard status text.",             "error(${1:status}, ${2:msg})"),
        fn("file",     "web.file(path) -> response",         "Streams the file at `path` (with Content-Type sniffing) to the client.",  "file(${1:path})"),
        fn("view",     "web.view(path, ctx) -> response",    "Render template at `path` with `ctx`, return as text/html.",                "view(${1:path}, ${2:ctx})"),

        // templates
        fn("set_views",         "web.set_views(dir) -> null",       "Set the templates directory used by `view`.", "set_views(${1:dir})"),
        fn("clear_views_cache", "web.clear_views_cache() -> null",  "Clear the template cache.",                    "clear_views_cache()"),

        // request body / upgrade helpers
        fn("upgrade",    "web.upgrade(req) -> ws_conn",      "Upgrade an HTTP request to a WebSocket; returns the WS connection.", "upgrade(${1:req})"),
        fn("parse_form", "web.parse_form(req) -> map",       "Parse `req.body` as form-urlencoded.",                                 "parse_form(${1:req})"),
        fn("parse_json", "web.parse_json(req) -> any",       "Parse `req.body` as JSON.",                                            "parse_json(${1:req})"),

        // servers
        fn("serve",
           "web.serve(opts, handler) -> listener",
           "Start an HTTP(S) server. `opts` may contain {port, tls, max_body_size, idle_timeout}. `handler(req)` returns a response.",
           "serve(${1:opts}, function (req) { ${0} })"),
        fn("serve_stream",
           "web.serve_stream(opts, handler) -> listener",
           "Streaming variant: the handler receives `req.body_stream.on_chunk(fn) / on_end(fn)` and calls `req.respond(r)` when done.",
           "serve_stream(${1:opts}, function (req) { ${0} })"),

        // app builder
        fn("app",
           "web.app() -> app",
           "Returns an app object with `.get/.post/.put/.patch/.delete/.head/.any/.route`, `.before/.after`, `.on_404/.on_error`, `.static`, `.listen`.",
           "app()"),
    ],
};

// built-in modules surfaced inside `import "..."`
export type BuiltinImport = { alias: string; phonetic: string[]; doc: string };

export const BUILTIN_IMPORTS: Record<string, BuiltinImport> = {
    // native modules
    sys:       { alias: "সিস্টেম",   phonetic: ["sistem", "system"],     doc: "Platform info, argv, env, exit." },
    timers:    { alias: "টাইমার",    phonetic: ["taimar", "timer"],      doc: "One-shot and repeating timers." },
    net:       { alias: "নেট",        phonetic: ["net"],                  doc: "TCP / UDP networking." },
    json:      { alias: "জেসন",      phonetic: ["jeson", "json"],        doc: "JSON encode and decode." },
    time:      { alias: "সময়",      phonetic: ["somoy", "somay"],       doc: "Time, dates, durations." },
    path:      { alias: "পথ",         phonetic: ["poth", "path"],         doc: "Path manipulation (join, dirname, basename)." },
    math:      { alias: "গণিত",      phonetic: ["gonit", "math"],        doc: "Math functions and constants." },
    random:    { alias: "এলোমেলো",  phonetic: ["elomelo", "random"],    doc: "Random number generation." },
    crypto:    { alias: "ক্রিপ্টো",  phonetic: ["kripto", "crypto"],     doc: "Hashes, HMAC, symmetric crypto." },
    regex:     { alias: "প্যাটার্ন",  phonetic: ["pattern", "patern"],    doc: "Regular-expression matching." },
    http:      { alias: "এইচটিটিপি", phonetic: ["http"],                 doc: "HTTP client and server." },
    tls:       { alias: "টিএলএস",    phonetic: ["tls"],                  doc: "TLS / SSL transport." },

    // library modules
    io:        { alias: "ফাইল",       phonetic: ["fail", "file"],         doc: "File and stream I/O (sync + async)." },
    request:   { alias: "অনুরোধ",    phonetic: ["onurodh", "request"],   doc: "High-level HTTP request helper." },
    web:       { alias: "ওয়েব",     phonetic: ["web", "oyeb"],          doc: "Web server framework." },
    url:       { alias: "ইউআরএল",    phonetic: ["url"],                  doc: "URL parsing and building." },
    log:       { alias: "লগ",         phonetic: ["log"],                  doc: "Logging." },
    test:      { alias: "টেস্ট",     phonetic: ["test", "tesht"],        doc: "Test runner / assertions." },
    zlib:      { alias: "সংকোচন",   phonetic: ["shongkochon", "zlib"],  doc: "Compression and decompression." },
    sqlite:    { alias: "এসকিউলাইট", phonetic: ["sqlite"],               doc: "SQLite database." },
    pg:        { alias: "পোস্টগ্রেস", phonetic: ["pg", "postgres"],       doc: "PostgreSQL client." },
    mysql:     { alias: "মাইএসকিউএল", phonetic: ["mysql"],                doc: "MySQL client." },
    mongo:     { alias: "মঙ্গো",     phonetic: ["mongo"],                doc: "MongoDB client." },
    exec:      { alias: "চালান",     phonetic: ["chalan", "exec"],       doc: "Subprocess execution." },
    dns:       { alias: "ডিএনএস",    phonetic: ["dns"],                  doc: "DNS resolution." },
    template:  { alias: "টেমপ্লেট",  phonetic: ["template", "templet"],  doc: "Template rendering." },
    ws:        { alias: "ওয়েবসকেট", phonetic: ["ws", "websocket"],      doc: "WebSocket client and server." },
    cookie:    { alias: "কুকি",       phonetic: ["kuki", "cookie"],       doc: "HTTP cookie parsing and serialization." },
    session:   { alias: "অধিবেশন",  phonetic: ["odhibeshon", "session"], doc: "HTTP session storage." },
    multipart: { alias: "মাল্টিপার্ট", phonetic: ["multipart"],            doc: "Multipart form parsing." },
    dotenv:    { alias: "ডটএনভ",     phonetic: ["dotenv"],               doc: "Load environment from .env files." },
    cli:       { alias: "কমান্ড",    phonetic: ["command", "kommand", "cli"], doc: "Command-line argument parsing." },
    uuid:      { alias: "ইউইউআইডি",  phonetic: ["uuid"],                 doc: "UUID generation." },
    csv:       { alias: "সিএসভি",    phonetic: ["csv"],                  doc: "CSV parsing and writing." },
};

// intrinsics on string / list / map values

export const STRING_INTRINSICS: Member[] = [
    fn("length",       ".length: number",                       "Codepoint count."),
    fn("byte_length",  ".byte_length: number",                  "Byte count (UTF-8)."),
    fn("byte_at",      ".byte_at(i) -> number",                 "Byte at index i.",                                 "byte_at(${1:i})"),
    fn("byte_slice",   ".byte_slice(start, end?) -> string",    "Byte-level substring.",                            "byte_slice(${1:start}, ${2:end})"),
    fn("slice",        ".slice(start, end?) -> string",         "Codepoint-aware substring.",                       "slice(${1:start}, ${2:end})"),
    fn("char_at",      ".char_at(i) -> string",                 "i-th codepoint as a 1-char string.",               "char_at(${1:i})"),
    fn("index_of",     ".index_of(needle, start?) -> number",   "First index of needle, or -1.",                    "index_of(${1:needle})"),
    fn("starts_with",  ".starts_with(s) -> bool",               "",                                                 "starts_with(${1:prefix})"),
    fn("ends_with",    ".ends_with(s) -> bool",                 "",                                                 "ends_with(${1:suffix})"),
    fn("split",        ".split(sep) -> list",                   "Empty sep splits to codepoints.",                  "split(${1:sep})"),
    fn("trim",         ".trim() -> string",                     "Strip ASCII whitespace.",                          "trim()"),
    fn("to_lower",     ".to_lower() -> string",                 "ASCII only.",                                      "to_lower()"),
    fn("to_upper",     ".to_upper() -> string",                 "ASCII only.",                                      "to_upper()"),
    fn("replace",      ".replace(needle, with) -> string",      "Replaces all occurrences.",                        "replace(${1:needle}, ${2:replacement})"),
];

export const LIST_INTRINSICS: Member[] = [
    fn("length", ".length: number"),
    fn("push",   ".push(v) -> null",       "Append; mutates in place.", "push(${1:value})"),
    fn("pop",    ".pop() -> any",          "Remove and return last; null if empty.", "pop()"),
];

export const MAP_INTRINSICS: Member[] = [
    fn("size",  ".size: number",       "Entry count (shadows any literal `size` key)."),
    fn("has",   ".has(k) -> bool",     "",                "has(${1:key})"),
    fn("keys",  ".keys() -> list",     "Returns the list of keys.", "keys()"),
];

// import name → canonical module key
export const IMPORT_NAME_TO_CANONICAL: Record<string, string> = {
    "io":         "io",
    "ফাইল":       "io",
    "sys":        "sys",
    "সিস্টেম":    "sys",
    "timers":     "timers",
    "টাইমার":     "timers",
    "time":       "time",
    "সময়":       "time",
    "url":        "url",
    "ইউআরএল":     "url",
    "path":       "path",
    "পথ":         "path",
    "math":       "math",
    "গণিত":       "math",
    "json":       "json",
    "জেসন":       "json",
    "log":        "log",
    "লগ":         "log",
    "exec":       "exec",
    "চালান":      "exec",
    "web":        "web",
    "ওয়েব":      "web",
    "mysql":      "mysql",
    "মাইএসকিউএল": "mysql",
    "pg":         "pg",
    "পোস্টগ্রেস": "pg",
    "sqlite":     "sqlite",
    "এসকিউলাইট":  "sqlite",
    "mongo":      "mongo",
    "মঙ্গো":      "mongo",
    "request":    "request",
    "অনুরোধ":     "request",
    "random":     "random",
    "এলোমেলো":   "random",
    "uuid":       "uuid",
    "ইউইউআইডি":   "uuid",
    "crypto":     "crypto",
    "ক্রিপ্টো":   "crypto",
    "csv":        "csv",
    "সিএসভি":     "csv",
    "cookie":     "cookie",
    "কুকি":        "cookie",
    "session":    "session",
    "অধিবেশন":   "session",
    "ws":         "ws",
    "ওয়েবসকেট":  "ws",
    "test":       "test",
    "টেস্ট":      "test",
    "net":        "net",
    "নেট":         "net",
    "http":       "http",
    "এইচটিটিপি":  "http",
    "tls":        "tls",
    "টিএলএস":     "tls",
    "regex":      "regex",
    "প্যাটার্ন":   "regex",
    "zlib":       "zlib",
    "সংকোচন":    "zlib",
    "dns":        "dns",
    "ডিএনএস":     "dns",
    "template":   "template",
    "টেমপ্লেট":   "template",
    "multipart":  "multipart",
    "মাল্টিপার্ট": "multipart",
    "dotenv":     "dotenv",
    "ডটএনভ":      "dotenv",
    "cli":        "cli",
    "কমান্ড":     "cli",
};
